apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec: 
  template:
    metadata:
      lables:
        app: mongodb
  spec:
    containers:
      - name: mongodb
        image: mongo.3.6.5-jessie

  replicas: 1
  selector:
    matchLables:
      app: mongodb

---
apiVersion: v1
kind: Service
metadata: 
  name: fleetman-mongodb
spec:
  ports:
    - name: mongodb
      port: 27017
  selector:
    app: mongodb

