apiVersion: v1

kind: Service

metadata: 
  name: fleetman-queue

spec:
  
  ports:
    - name: http
      port: 8161
      nodePort: 30010
     
    - name: endpoint
      port: 61616
      
  selector:
    app: queue

     
