apiVersion: v1

kind: Service

metadata: 
  name: fleetman-queue

spec:
  type: NodePort
  ports:
    - name: http
      port: 8161
      nodeport: 30010
     
    - name: endpoint
      port: 61616
      
  selector:
    app: queue

     