apiVersion: v1

kind: Service

metadata: fleetman-queue

spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8161
      LoadBalancer: 80

    - name: endpoint
      port: 61616

   selector:
      app: queue

     