apiVersion: v1

kind: Service

metadata: 
  name: fleetman-queue

spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8161
   
  type: ClusterIP   
  ports:
    - name: endpoint
      port: 61616
      

  selector:
    app: queue

     