apiVersion: v1

kind: Service

metadata: 
  name: fleetman-queue

spec:
  
  ports:
    - name: endpoint
      port: 61616
      
  selector:
    app: queue

---
apiVersion: v1

kind: Service

metadata: 
  name: fleetman-queue-web

spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8161
      
  selector:
    app: queue

---
apiVersion: v1
kind: Service
metadata: 
  name: fleetman-position-tracker
spec:
  
  ports:
    - name: rest
      port: 8080
      
  selector:
    app: position-tracker

     
