apiVersion: apps/v1
kind: Deployment 
metadata:
  name: queue

spec: 
  template:
    metadata: 
      labels:
        app: queue
    spec:
      containers:
      - name: queue
        image: richardchesterwood/k8s-fleetman-queue:release1

  replicas: 1

  selector:
    matchLabels:
      app:  queue

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-simulator
spec: 
  template:
    metadata:
      labels:
        app: position-simulator
    spec:
      containers:
        - name: position-simulator
          image: richardchesterwood/k8s-fleetman-position-simulator:release1
          env: 
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice
    
  replicas: 1

  selector:
    matchLabels:
      app: position-simulator

---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: position-tracker
spec:
  template:
    metadata:
      labels:
        app: position-tracker
    spec:
      containers:
        - name: position-tracker
          image: richardchesterwood/k8s-fleetman-position-tracker:release1
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice
  replicas: 1

  selector:
    matchLabels:
      app: position-tracker

---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: api-gateway
spec:
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: richardchesterwood/k8s-fleetman-api-gateway:release1
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice
  replicas: 1

  selector:
    matchLabels:
      app: api-gateway

---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: webapp
spec:
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: richardchesterwood/k8s-fleetman-webapp-angular:release1
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice
  replicas: 1

  selector:
    matchLabels:
      app: webapp
            