apiVersion: apps/v1
kind: Deployment 
metadata:
  name: queue

spec: 
  template:
    metadata: 
      labels:
        app: queue
    spec:
      containers:
      - name: queue
        image: richardchesterwood/k8s-fleetman-queue:release1

  replicas: 1

  selector:
    matchLabels:
      app:  queue
